services:
  web:
    image: odoo:20
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data-20:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    env_file:
      - .env
    environment:
      - HOST=db
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
    command: odoo --log-handler odoo.addons.rpc.controllers.xmlrpc:ERROR
    restart: unless-stopped

  db:
    image: postgres:18
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - odoo-db-data-18:/var/lib/postgresql
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - db
    ports:
      - "5050:80"
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.16.1
    container_name: odoo-hr-mlflow
    ports:
      - "5000:5000"
    volumes:
      - mlflow-data:/mlflow
    command: mlflow server --backend-store-uri sqlite:////mlflow/mlflow.db --default-artifact-root /mlflow/artifacts --host 0.0.0.0 --port 5000
    restart: unless-stopped

volumes:
  odoo-web-data-20:
  odoo-db-data-18:
  pgadmin-data:
  mlflow-data:
